name: less_transformer
version: 0.1.0
description: >
  Pub transformer that translates LESS files into CSS using external tool.

dependencies:
  barback: ">=0.14.0 <0.17.0"
  quiver:  ">=0.18.2 <0.19.0"
