name: less_transformer
version: 0.1.0
author: Farata Systems LLC. <info@faratasystems.com>
homepage: https://github.com/Farata/dart-less-transformer

description: >
  Pub transformer that translates LESS files into CSS using external
  tool.

dependencies:
  barback: ">=0.14.2 <0.16.0"
  quiver:  ">=0.18.2 <0.19.0"
